@extends('backend.layouts.main')
@section('main-container')
<div class="main-content pt-4">
    <div class="breadcrumb d-flex justify-content-between align-items-center"><h1>Monthly Fuel Consumption</h1><a href="{{ route('transport.fuel.index') }}" class="btn btn-outline-secondary">Fuel Entries</a></div>
    <div class="separator-breadcrumb border-top"></div>
    <div class="card mb-4"><div class="card-body"><form method="GET" class="form-row align-items-end"><div class="form-group col-md-2"><label>Month</label><select name="month" class="form-control">@for($i=1;$i<=12;$i++)<option value="{{ $i }}" @selected($month === $i)>{{ \Carbon\Carbon::create()->month($i)->format('F') }}</option>@endfor</select></div><div class="form-group col-md-2"><label>Year</label><input name="year" type="number" class="form-control" value="{{ $year }}" min="2000" max="2100"></div><div class="form-group col-md-3"><label>Vehicle</label><select name="vehicle_id" class="form-control"><option value="">All vehicles</option>@foreach($vehicles as $vehicle)<option value="{{ $vehicle->id }}" @selected(request('vehicle_id') == $vehicle->id)>{{ $vehicle->vehicelno }}</option>@endforeach</select></div><div class="form-group col-md-2"><label>Fuel Type</label><select name="fuel_type" class="form-control"><option value="">All types</option>@foreach(['Diesel','Petrol','CNG','Electric','Other'] as $type)<option @selected(request('fuel_type') === $type)>{{ $type }}</option>@endforeach</select></div><div class="form-group col-md-2"><button class="btn btn-primary">Generate</button></div></form></div></div>
    <div class="card"><div class="card-body"><h3>{{ \Carbon\Carbon::create($year, $month, 1)->format('F Y') }}</h3><div class="table-responsive"><table class="table table-striped table-bordered"><thead><tr><th>S.No.</th><th>Vehicle No.</th><th>Fuel Type</th><th>Total Quantity</th><th>Unit</th><th>Average Rate</th><th>Total Amount</th><th>Starting KM</th><th>Last KM</th><th>Difference</th><th>Average / Efficiency</th></tr></thead><tbody>@forelse($report as $key => $row)<tr><td>{{ $key + 1 }}</td><td>{{ $row->vehicelno }}</td><td>{{ $row->fuel_type }}</td><td>{{ number_format($row->total_quantity, 2) }}</td><td>{{ $row->quantity_unit }}</td><td>{{ number_format($row->average_rate, 2) }}</td><td>{{ number_format($row->total_amount, 2) }}</td><td>{{ number_format($row->starting_km, 2) }}</td><td>{{ number_format($row->last_km, 2) }}</td><td>{{ number_format($row->last_km - $row->starting_km, 2) }}</td><td>{{ $row->efficiency !== null ? number_format($row->efficiency, 2).' KM/'.$row->quantity_unit : 'N/A' }}</td></tr>@empty<tr><td colspan="11" class="text-center">No fuel records found for the selected period.</td></tr>@endforelse</tbody></table></div></div></div>
</div>
@endsection
